"""Deterministic, representation-neutral scaled combat contracts."""

from .models import (
    BattleKernel,
    CapabilityProfile,
    CombatContract,
    CombatEffectPlan,
    CombatIntent,
    CombatObjective,
    CombatTiming,
    Engagement,
    ExchangeEffect,
    InformationState,
    ObjectiveEffect,
    Participant,
    ParticipantEffect,
    PersonnelState,
    PositionState,
    ResourceCost,
    ResourcePool,
    SideTerrain,
    SuccessorBoundary,
    TerrainState,
    WakeTrigger,
)
from .resolver import (
    CombatContractError,
    CombatRNGError,
    required_draw_count,
    resolve_combat,
)

__all__ = [
    "BattleKernel",
    "CapabilityProfile",
    "CombatContract",
    "CombatContractError",
    "CombatEffectPlan",
    "CombatIntent",
    "CombatObjective",
    "CombatRNGError",
    "CombatTiming",
    "Engagement",
    "ExchangeEffect",
    "InformationState",
    "ObjectiveEffect",
    "Participant",
    "ParticipantEffect",
    "PersonnelState",
    "PositionState",
    "ResourceCost",
    "ResourcePool",
    "SideTerrain",
    "SuccessorBoundary",
    "TerrainState",
    "WakeTrigger",
    "required_draw_count",
    "resolve_combat",
]
