"""Canonical repository paths used by semantic command domains.

Path constants live here so domain modules do not duplicate repository routing
strings.  These constants identify storage locations only; gameplay authority
still belongs to the referenced owner/schema.
"""

WORLD_EVENT_REGISTRY_PATH = "state/reg/world-events.json"
INFORMATION_REGISTRY_PATH = "state/reg/information-deliveries.json"
COMMITMENT_REGISTRY_PATH = "state/reg/commitments.json"
CUSTODY_REGISTRY_PATH = "state/reg/custody.json"
CONFLICT_REGISTRY_PATH = "state/conflict/registry.json"
COMBAT_ZOOM_REGISTRY_PATH = "state/reg/combat-zoom.json"
ASSIGNMENTS_PATH = "state/org/assignments.json"
POPULATION_REGISTRY_PATH = "state/population/registry.json"
DEVELOPMENT_BANK_PATH = "state/development/banks.json"
PERSON_CONTINUITY_PATH = "state/reg/person-continuity.json"
ROUTES_PATH = "state/world/routes-and-settlements.json"
TRAVEL_MECHANICS_PATH = "game/data/mechanics/travel.json"
CONFLICT_MECHANICS_PATH = "game/data/mechanics/conflict.json"
FORMATION_TENDENCY_PROFILES_PATH = "game/data/organization/formation-tendency-profiles.json"
TRAINING_MODELS_PATH = "game/rules/training/models.json"
TEAM_TYPES_PATH = "game/data/team/team-types.json"
RECRUITMENT_POLICIES_PATH = "game/rules/recruitment/policies.json"
DEMOGRAPHY_POLICY_PATH = "game/rules/population/demography.json"
RECOVERY_POLICY_PATH = "game/rules/health/recovery.json"
AUTONOMY_POLICY_PATH = "game/rules/autonomy/policies.json"
RELATIONSHIP_RULES_PATH = "game/rules/relationships/interactions.json"
RELATIONSHIP_INDEX_PATH = "state/reg/relationship-edge-index.json"
NAMED_ITEMS_PATH = "state/reg/named-items.json"
INVENTORY_REGISTRY_PATH = "state/inventory/registry.json"
LOADOUT_INDEX_PATH = "game/data/loadout-records/index.json"
STOCK_ALIAS_PATH = "game/data/items/stock-aliases.json"
STOCK_OWNER_PATHS = "game/data/items/stock-owner-paths.json"
DOMAIN_REGISTRY_PATH = "state/reg/missions-contracts-projects.json"
INSTITUTION_PROJECT_MECHANICS_PATH = "game/data/mechanics/institution-projects.json"
ECONOMY_MECHANICS_PATH = "game/data/mechanics/economy.json"
ITEM_INDEX_PATH = "game/data/items/index.json"
ECONOMY_WORLD_PATH = "state/world/economies-and-mission-markets.json"
MEDICAL_MECHANICS_PATH = "game/data/mechanics/medical.json"
MEDICAL_IMPLANT_PROFILES_PATH = "game/data/medical/implants.json"
BIOLOGICAL_IMPLANTS_PATH = "state/medical/biological-implants.json"
OCULAR_REGISTRY_PATH = "state/medical/ocular-registry.json"
REPUTATION_SUBJECT_ROOT = "state/reputation/subjects"
REPUTATION_AUDIENCE_ROOT = "state/reputation/audiences"
REPUTATION_EVENT_ROOT = "state/reputation/events"
TECHNIQUE_MANIFEST_PATH = "game/data/tech/manifest.json"
TECHNIQUE_LEARNING_PATH = "game/data/mechanics/technique-learning.json"
REPUTATION_MECHANICS_PATH = "game/data/mechanics/reputation.json"
REPUTATION_SIGNALS_PATH = "game/data/reputation/event-signals.json"
REPUTATION_INDEX_PATH = "state/reputation/index.json"
FAMILY_INDEX_PATH = "state/family/index.json"
KINSHIP_INDEX_PATH = "state/family/kinship-index.json"
SPECIAL_SYSTEMS_PATH = "game/data/mechanics/special-systems.json"
BIJU_MECHANICS_PATH = "game/data/mechanics/biju.json"
JINCHURIKI_REGISTRY_PATH = "state/reg/jinchuriki.json"
PUPPET_REGISTRY_PATH = "state/reg/puppets.json"
SUMMON_REGISTRY_PATH = "state/reg/summons.json"

