from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'runtime/shinobi_runtime/martial_world/exact_combat.py'
TEST=ROOT/'tests/current/test_exact_combat_withdrawal.py'

text=SOURCE.read_text(encoding='utf-8')

old='''    if escaped:\n        statuses={str(x) for x in state.get("status_families",[]) if isinstance(x,str)}; statuses.add("escaped"); state["status_families"]=sorted(statuses)\n    return {"moved":True,"escaped":escaped,"reason":"cleared_opponent_reach" if escaped else "retreat_in_progress","corridor":chosen,"movement":{"start_x_mm":start_x,"start_y_mm":start_y,"end_x_mm":end_x,"end_y_mm":end_y,"duration_ms":duration,"nearest_enemy_mm":nearest}}\n\n\ndef resolve_exchange'''
new='''    if escaped:\n        statuses={str(x) for x in state.get("status_families",[]) if isinstance(x,str)}; statuses.add("escaped"); state["status_families"]=sorted(statuses)\n        state["escaped_at_ms"]=int(start_ms)+duration\n    return {"moved":True,"escaped":escaped,"reason":"cleared_opponent_reach" if escaped else "retreat_in_progress","corridor":chosen,"movement":{"start_x_mm":start_x,"start_y_mm":start_y,"end_x_mm":end_x,"end_y_mm":end_y,"duration_ms":duration,"nearest_enemy_mm":nearest}}\n\n\ndef _resolve_withdrawal_batch(*, combat: dict[str, Any], withdrawer_refs: Sequence[str], people: dict[str, dict[str, Any]], equipment_ledger: Mapping[str, Any], start_ms: int, end_ms: int) -> list[dict[str, Any]]:\n    """Settle concurrent autonomous withdrawals at one shared timeline boundary."""\n    end=max(int(start_ms),int(end_ms))\n    _settle_combat_physiology_until(combat,people,target_ms=max(int(combat.get("elapsed_ms",0)),end),equipment_ledger=equipment_ledger)\n    events=[]\n    for ref in withdrawer_refs:\n        state=combat.get("combatants",{}).get(ref)\n        if ref not in people or not isinstance(state,dict) or not _active(people[ref],state):\n            interrupted_at=state.get("incapacitated_at_ms") if isinstance(state,Mapping) else None\n            at=max(int(start_ms),min(end,int(interrupted_at))) if isinstance(interrupted_at,int) else end\n            events.append({"actor_ref":ref,"result":"withdrawal_interrupted","decision_origin":"actor_ai","started_at_ms":int(start_ms),"ended_at_ms":at})\n            continue\n        step=_disengage_step(combat=combat,actor_ref=ref,people=people,equipment_ledger=equipment_ledger,duration_ms=max(1,end-int(start_ms)),start_ms=int(start_ms))\n        events.append({"actor_ref":ref,"result":("withdrew_from_combat" if step.get("escaped") else "withdrawal_in_progress" if step.get("moved") else "withdrawal_blocked"),"decision_origin":"actor_ai","started_at_ms":int(start_ms),"ended_at_ms":end,"withdrawal":step})\n    return events\n\n\ndef resolve_exchange'''
assert text.count(old)==1, text.count(old)
text=text.replace(old,new,1)

old='''    active_at_declaration=[ref for refs in out["sides"].values() for ref in refs if _active(persons[ref],out["combatants"][ref])]; scheduled=[]; declaration_events=[]; withdrawing=[]\n    for actor_ref in active_at_declaration:\n        side=_side_of(out,actor_ref); enemy_side="side_b" if side=="side_a" else "side_a"; enemies=[ref for ref in out["sides"][enemy_side] if _active(persons[ref],out["combatants"][ref])]\n        if actor_ref!=player_ref:\n            withdrawal=_npc_withdrawal_decision(combat=out,actor_ref=actor_ref,people=persons,faction_doctrine=doctrines.get(str(persons[actor_ref].get("faction_ref") or ""),{}))\n            if withdrawal is not None:\n                withdrawing.append(actor_ref); declaration_events.append({"actor_ref":actor_ref,"result":"withdrawal_declared","decision_origin":"actor_ai","declared_at_ms":int(out.get("elapsed_ms",0)),"withdrawal":withdrawal}); continue\n        known=_observe_visible_enemies(out,actor_ref=actor_ref,enemy_refs=enemies,people=persons,at_ms=int(out.get("elapsed_ms",0)))\n'''
new='''    declared_exchange_ms=int(out.get("elapsed_ms",0))\n    active_at_declaration=[ref for refs in out["sides"].values() for ref in refs if _active(persons[ref],out["combatants"][ref])]; scheduled=[]; declaration_events=[]; withdrawing=[]\n    # Withdrawal is a declaration-time intent. Mark every withdrawing actor\n    # before scheduling anyone else's action so pursuit doctrine sees the same\n    # physical posture regardless of side/list iteration order.\n    for actor_ref in active_at_declaration:\n        if actor_ref==player_ref: continue\n        withdrawal=_npc_withdrawal_decision(combat=out,actor_ref=actor_ref,people=persons,faction_doctrine=doctrines.get(str(persons[actor_ref].get("faction_ref") or ""),{}))\n        if withdrawal is None: continue\n        withdrawing.append(actor_ref)\n        out["positions"][actor_ref]["stance"]="disengaging"\n        declaration_events.append({"actor_ref":actor_ref,"result":"withdrawal_declared","decision_origin":"actor_ai","declared_at_ms":declared_exchange_ms,"withdrawal":withdrawal})\n    for actor_ref in active_at_declaration:\n        if actor_ref in withdrawing: continue\n        side=_side_of(out,actor_ref); enemy_side="side_b" if side=="side_a" else "side_a"; enemies=[ref for ref in out["sides"][enemy_side] if _active(persons[ref],out["combatants"][ref])]\n        known=_observe_visible_enemies(out,actor_ref=actor_ref,enemy_refs=enemies,people=persons,at_ms=int(out.get("elapsed_ms",0)))\n'''
assert text.count(old)==1, text.count(old)
text=text.replace(old,new,1)

old='''    if actor_ref not in people or target_ref not in people: return {**event_base,"result":"invalid_target"}\n    _settle_combat_physiology_until(combat,people,target_ms=action.contact_at_ms,equipment_ledger=equipment_ledger)\n    actor_state=combat["combatants"][actor_ref]; target_state=combat["combatants"][target_ref]; disabled_at=actor_state.get("incapacitated_at_ms")\n'''
new='''    if actor_ref not in people or target_ref not in people: return {**event_base,"result":"invalid_target"}\n    target_state_pre=combat.get("combatants",{}).get(target_ref,{})\n    escaped_at=target_state_pre.get("escaped_at_ms") if isinstance(target_state_pre,Mapping) else None\n    # A target that physically cleared the fight before this attack committed\n    # ends the uncommitted chase at that frontier. Already-committed/released\n    # attacks remain on the shared timeline and resolve against moved geometry.\n    if isinstance(escaped_at,int) and escaped_at<int(action.commit_at_ms):\n        if int(combat.get("elapsed_ms",0))<escaped_at:\n            _settle_combat_physiology_until(combat,people,target_ms=escaped_at,equipment_ledger=equipment_ledger)\n        return {**event_base,"result":"target_escaped_before_commitment","escaped_at_ms":escaped_at}\n    _settle_combat_physiology_until(combat,people,target_ms=action.contact_at_ms,equipment_ledger=equipment_ledger)\n    actor_state=combat["combatants"][actor_ref]; target_state=combat["combatants"][target_ref]; disabled_at=actor_state.get("incapacitated_at_ms")\n'''
assert text.count(old)==1, text.count(old)
text=text.replace(old,new,1)

old='''    scheduled.sort(key=lambda row:(row.contact_at_ms,row.commit_at_ms,-_combat_capability_for_state(row.actor_ref,persons[row.actor_ref],ledger,out["combatants"].get(row.actor_ref,{})).reaction,row.actor_ref)); events=list(declaration_events); exchange_end=int(out.get("elapsed_ms",0))\n    out["_exchange_declared_at_ms"] = int(out.get("elapsed_ms", 0))\n    out["_pending_actions"] = {action.actor_ref: _pending_action_record(action) for action in scheduled}\n    out["_defense_interruptions"] = {}\n    for action in scheduled:\n        event=_resolve_scheduled_action(combat=out,action=action,people=persons,equipment_ledger=ledger); events.append(event); exchange_end=max(exchange_end,action.contact_at_ms)\n        pending = out.get("_pending_actions", {})\n        if isinstance(pending, dict):\n            pending.pop(action.actor_ref, None)\n    declared_exchange_ms=int(combat.get("elapsed_ms",0))\n    if exchange_end<=declared_exchange_ms:\n        exchange_end=declared_exchange_ms+max(1,int(_combat_rules().get("minimum_exchange_advance_ms",250)))\n    _settle_combat_physiology_until(out,persons,target_ms=max(int(out.get("elapsed_ms",0)),exchange_end),equipment_ledger=ledger)\n    out.pop("_pending_actions", None)\n    out.pop("_defense_interruptions", None)\n    out.pop("_exchange_declared_at_ms", None)\n    surviving_withdrawers=[ref for ref in withdrawing if ref in persons and ref in out.get("combatants",{}) and _active(persons[ref],out["combatants"][ref])]\n    if surviving_withdrawers:\n        withdrawal_start=int(out.get("elapsed_ms",0)); withdrawal_end=withdrawal_start+1000\n        for ref in withdrawing:\n            if ref not in surviving_withdrawers:\n                events.append({"actor_ref":ref,"result":"withdrawal_interrupted","decision_origin":"actor_ai","started_at_ms":withdrawal_start,"ended_at_ms":withdrawal_start}); continue\n            step=_disengage_step(combat=out,actor_ref=ref,people=persons,equipment_ledger=ledger,duration_ms=1000,start_ms=withdrawal_start)\n            events.append({"actor_ref":ref,"result":("withdrew_from_combat" if step.get("escaped") else "withdrawal_in_progress" if step.get("moved") else "withdrawal_blocked"),"decision_origin":"actor_ai","started_at_ms":withdrawal_start,"ended_at_ms":withdrawal_end,"withdrawal":step})\n        _settle_combat_physiology_until(out,persons,target_ms=withdrawal_end,equipment_ledger=ledger)\n    elif withdrawing:\n        withdrawal_start=int(out.get("elapsed_ms",0))\n        for ref in withdrawing: events.append({"actor_ref":ref,"result":"withdrawal_interrupted","decision_origin":"actor_ai","started_at_ms":withdrawal_start,"ended_at_ms":withdrawal_start})\n'''
new='''    scheduled.sort(key=lambda row:(row.contact_at_ms,row.commit_at_ms,-_combat_capability_for_state(row.actor_ref,persons[row.actor_ref],ledger,out["combatants"].get(row.actor_ref,{})).reaction,row.actor_ref)); events=list(declaration_events); exchange_end=declared_exchange_ms\n    out["_exchange_declared_at_ms"] = declared_exchange_ms\n    out["_pending_actions"] = {action.actor_ref: _pending_action_record(action) for action in scheduled}\n    out["_defense_interruptions"] = {}\n    withdrawal_end=declared_exchange_ms+1000 if withdrawing else None\n    withdrawal_pending=bool(withdrawing)\n    for action in scheduled:\n        # Retreat completes at its own one-second frontier. Contacts at the exact\n        # same millisecond resolve first; contacts strictly later see the moved\n        # target and may be cancelled if they had not yet committed.\n        if withdrawal_pending and isinstance(withdrawal_end,int) and withdrawal_end<int(action.contact_at_ms):\n            events.extend(_resolve_withdrawal_batch(combat=out,withdrawer_refs=withdrawing,people=persons,equipment_ledger=ledger,start_ms=declared_exchange_ms,end_ms=withdrawal_end))\n            exchange_end=max(exchange_end,withdrawal_end); withdrawal_pending=False\n        event=_resolve_scheduled_action(combat=out,action=action,people=persons,equipment_ledger=ledger); events.append(event)\n        exchange_end=max(exchange_end,int(out.get("elapsed_ms",0)))\n        pending = out.get("_pending_actions", {})\n        if isinstance(pending, dict):\n            pending.pop(action.actor_ref, None)\n    if withdrawal_pending and isinstance(withdrawal_end,int):\n        events.extend(_resolve_withdrawal_batch(combat=out,withdrawer_refs=withdrawing,people=persons,equipment_ledger=ledger,start_ms=declared_exchange_ms,end_ms=withdrawal_end))\n        exchange_end=max(exchange_end,withdrawal_end)\n    if exchange_end<=declared_exchange_ms:\n        exchange_end=declared_exchange_ms+max(1,int(_combat_rules().get("minimum_exchange_advance_ms",250)))\n    _settle_combat_physiology_until(out,persons,target_ms=max(int(out.get("elapsed_ms",0)),exchange_end),equipment_ledger=ledger)\n    out.pop("_pending_actions", None)\n    out.pop("_defense_interruptions", None)\n    out.pop("_exchange_declared_at_ms", None)\n'''
assert text.count(old)==1, text.count(old)
text=text.replace(old,new,1)
SOURCE.write_text(text,encoding='utf-8')

test=TEST.read_text(encoding='utf-8')
test=test.replace("    assert result['combat_after']['elapsed_ms']==1250\n", "    assert result['combat_after']['elapsed_ms']==1000\n", 1)
test=test.replace("    assert {event['started_at_ms'] for event in moved}=={250}\n    assert {event['ended_at_ms'] for event in moved}=={1250}\n", "    assert {event['started_at_ms'] for event in moved}=={0}\n    assert {event['ended_at_ms'] for event in moved}=={1000}\n", 1)
addition=r'''\n\ndef test_withdrawal_completion_cancels_late_uncommitted_chase_on_shared_clock():\n    base=load('state/martial-world/people/house_tang.json')['people'][0]\n    player=person(base,'timeline.player','faction.player'); survivor=person(base,'timeline.survivor','faction.withdraw'); casualty=person(base,'timeline.casualty','faction.withdraw')\n    casualty['health'].update(status='dead',consciousness=0)\n    people={row['person_id']:row for row in (player,survivor,casualty)}; gear=ledger(*people)\n    combat=initialize_combat(combat_ref='withdraw-timeline',side_a_refs=[player['person_id']],side_b_refs=[survivor['person_id'],casualty['person_id']],people=people,zone_ref='site.house_tang',started_at='x',objective={'kind':'eliminate'},equipment_ledger=gear)\n    combat['positions'][player['person_id']].update(x_mm=0,y_mm=0)\n    combat['positions'][survivor['person_id']].update(x_mm=20000,y_mm=0)\n    result=resolve_exchange(combat=combat,people=people,equipment_ledger=gear,doctrines={'faction.withdraw':doctrine()},player_ref=player['person_id'],player_action_kind='unarmed_strike',player_target_ref=survivor['person_id'],player_weapon_ref='body_unarmed',player_hit_zone='chest',player_targeting_intent='disable')\n    withdrawal=next(event for event in result['events'] if event.get('actor_ref')==survivor['person_id'] and event.get('result')=='withdrew_from_combat')\n    attack=next(event for event in result['events'] if event.get('actor_ref')==player['person_id'])\n    assert withdrawal['started_at_ms']==0 and withdrawal['ended_at_ms']==1000\n    assert attack['commit_at_ms']>1000\n    assert attack['result']=='target_escaped_before_commitment'\n    assert attack['escaped_at_ms']==1000\n    assert result['combat_after']['elapsed_ms']==1000\n'''
if 'test_withdrawal_completion_cancels_late_uncommitted_chase_on_shared_clock' not in test:
    test += addition
TEST.write_text(test,encoding='utf-8')
print('withdrawal timeline improvements applied')
