"""Pure deterministic gameplay reducers."""

from .health import HealthResolutionError, apply_personnel_effect, settle_recovery
from .information import InformationClaim, InformationDelivery, deliver_claim
from .missions import (
    LEGAL_MISSION_TRANSITIONS,
    LEGAL_OBJECTIVE_TRANSITIONS,
    MISSION_STATES,
    OBJECTIVE_KINDS,
    OBJECTIVE_STATUSES,
    TERMINAL_MISSION_STATES,
    TERMINAL_OBJECTIVE_STATUSES,
    Mission,
    MissionObjective,
    MissionSettlement,
    MissionTransitionError,
    ObjectiveDependencyError,
    SettlementConflictError,
    SettlementResult,
    SettlementTerm,
    derive_mission_outcome,
    settle_mission,
    transition_mission,
    update_objective,
)
from .population import (
    PopulationPool,
    PopulationTransfer,
    apply_transfer,
    neutral_proportional_selection,
    materialize_member,
)
from .training import TrainingInputs, TrainingOutcome, settle_training

__all__ = [
    "HealthResolutionError",
    "InformationClaim",
    "InformationDelivery",
    "LEGAL_MISSION_TRANSITIONS",
    "LEGAL_OBJECTIVE_TRANSITIONS",
    "MISSION_STATES",
    "Mission",
    "MissionObjective",
    "MissionSettlement",
    "MissionTransitionError",
    "ObjectiveDependencyError",
    "OBJECTIVE_KINDS",
    "OBJECTIVE_STATUSES",
    "PopulationPool",
    "PopulationTransfer",
    "SettlementConflictError",
    "SettlementResult",
    "SettlementTerm",
    "TERMINAL_MISSION_STATES",
    "TERMINAL_OBJECTIVE_STATUSES",
    "TrainingInputs",
    "TrainingOutcome",
    "apply_personnel_effect",
    "settle_recovery",
    "apply_transfer",
    "deliver_claim",
    "derive_mission_outcome",
    "neutral_proportional_selection",
    "materialize_member",
    "settle_training",
    "settle_mission",
    "transition_mission",
    "update_objective",
]
